### ISSUE TITLE
Running Issue: Run Time Error

### ISSUE THREAD

**Issue by 543090lee** [SFGLab/ConsensuSV-pipeline#2]
Hello, I ran ConsensuSV, and ran into following issue.
ERROR: [pid 1319] Worker Worker(salt=210304433, workers=4, host=4305d4cfaeb1, username=root, pid=25) failed    IndexBam(working_dir=/test_working_dir/, file_name_1=/tools/ERR018471_1.filt.fastq, file_name_2=/tools/ERR018471_2.filt.fastq, sample_name=ERR018471)
Traceback (most recent call last):
  File "/tools/anaconda/lib/python3.8/site-packages/luigi/worker.py", line 176, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: SortBam__tools_ERR018471__tools_ERR018471_ERR018471_244d949768
ERROR: [pid 1321] Worker Worker(salt=210304433, workers=4, host=4305d4cfaeb1, username=root, pid=25) failed    IndexBam(working_dir=/test_working_dir/, file_name_1=/tools/ERR018471_1.filt.fastq, file_name_2=/tools/ERR018471_2.filt.fastq, sample_name=ERR018471)
Traceback (most recent call last):
  File "/tools/anaconda/lib/python3.8/site-packages/luigi/worker.py", line 176, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: SortBam__tools_ERR018471__tools_ERR018471_ERR018471_244d949768

Thank you for help

**Comment by jdy4389** [comment]
I am getting the same error when attempting running the docker image and attempting ./test_run_fast.sh. Tasks 1-5 complete, and IndexBam fails with the above error.
